### PR TITLE
fixed dependency rename

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by abstractj** [comment]
@edewit how to test and reproduce the issue? Only to make sure that I'm not testing the wrong thing.

**Comment by edewit** [comment]
without this fix the plugin will not install but give an error

**Comment by danielpassos** [comment]
@bleathem Could you give it a spin? Let me know if you need some help!

**Comment by bleathem** [comment]
I verified that the renamed plugin dependency is correctly installed:

```
$ cordova create hello com.example.hello HelloWorld; cd hello/; cordova platform add android; cordova plugin add https://github.com/edewit/aerogear-crypto-cordova.git#dependency-fix; cordova plugin ls
Creating a new cordova project.
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android
Fetching plugin "https://github.com/edewit/aerogear-crypto-cordova.git" via git clone
Repository "https://github.com/edewit/aerogear-crypto-cordova.git" checked out to git ref "dependency-fix".
Installing "org.jboss.aerogear.cordova.crypto" for android
Fetching plugin "https://github.com/vstirbu/PromisesPlugin.git" via git clone
Repository "https://github.com/vstirbu/PromisesPlugin.git" checked out to git ref "master".
Installing "es6-promise-plugin" for android
cordova-plugin-whitelist 1.0.0 "Whitelist"
es6-promise-plugin 3.0.2 "Promise"
org.jboss.aerogear.cordova.crypto 0.0.1 "AeroGear Crypto Plugin"
```

This PR looks good!

**Comment by danielpassos** [comment]
Landed at https://github.com/aerogear/aerogear-cordova-crypto/commit/1a8fa9a9b91cf26bc04baa5fab8eecb1ab7bfd54

**Pull request closed without merging**
